[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
core = {path ="../"}
libp2p ={workspace = true}
seraphic = { workspace = true }
tokio ={workspace = true}
serde_json={workspace=true}
serde={workspace=true}
tracing ={workspace = true}
clap ={workspace = true}
