[package]
name = "macros"
version = "0.1.0"
edition = "2021"
[lib]
proc_macro = true
[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = {version= "2.0.90", features =["full"]}
trybuild = "1.0.101"
